services:
  web:
    image: remigirard.dev:5000/admin/neguenentropia_web:${STAGE_NAME}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.neguenentropia.rule=Host(`${DEPLOY_URL}`)"
        - "traefik.http.routers.neguenentropia.entrypoints=websecure"
        - "traefik.http.routers.neguenentropia.tls.certresolver=wildcardresolver"
        - "traefik.http.services.neguenentropia.loadbalancer.server.port=80"
networks:
  traefik-public:
    external: true